version: "3"
services:
  discord-bot:
    container_name: town-manager-bot
    build: .
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - town_manager_data:/app/data # Persist database in a dedicated volume

volumes:
  town_manager_data:
